### PR TITLE
Fixed bug, resolved #19 #20 #16

### LINKED ISSUE #19: Support Sketch 45 plugin update system
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

### PR DESCRIPTION
**Pull request by seanriceaz**
@swilliams Can you merge this in? It's a bug fix mostly...

### CODE REVIEW

**Comment by seanriceaz** [comment]
@isiegel @iortz-ethology Can you guys merge this? The fate of all designers using sketch depends on it!

Kidding... but please do merge this in when you can ;)

**Comment by isiegel** [comment]
Looks like I don't have write access to this repo.

This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

**Comment by seanriceaz** [comment]
@isiegel That's super lame! I don't have access anymore to merge anything. So... Whenever @swilliams is around, please let him know this is a a simple merge... Actually, if he gives me write access to this repo (since I'm trying to actively maintain it), that would be better :)

**Comment by seanriceaz** [comment]
maybe @paulvantuyl can merge it in? (Getting desperate here hahaha)

**Comment by isiegel** [comment]
You sure the fate of all designers using Sketch depends on it wasn't a joke? :)

**Comment by paulvantuyl** [comment]
Merged and I also added @seanriceaz as a contributor – hope you don’t care @swilliams. This is his baby, even if it’s Tallwave’s IP.

**Pull request merged**
